openapi: 3.0.3
info:
  title: PixLog Backend
  version: 1.0.0
  license:
    name: Pixlog
    url: https://pixlog.com.br/termos-de-uso.html
  description: Sistema de backend do PixLog, codificado em NodeJS com banco de dados
    em MySQL(MariaDB).
servers:
- url: https://api.pixlog.com.br
  description: Servidor de produção
- url: https://stage.pixlog.com.br
  description: Servidor de staging
paths:
  "/v1/user":
    post:
      summary: Cadastra um novo usuário.
      tags:
      - 'users: Usuários'
      operationId: createUser
      description: Utilize esta função para criar novos usuários na plataforma. Usuário
        é uma das entidades básicas do sistema.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/postV1Users"
            example:
              registration_data:
                name: Pixlog
                cpf: 627.820.760-51
                phone: "+55 41 99868-5562"
              login:
                email: dev@pixlog.com.br
                password: Dev@Pixlog2020
              address:
                level2long: CURITIBA
      responses:
        '201':
          description: Cliente cadastrado com sucesso.
          content:
            application/json:
              example:
                registration_data:
                  name: Pixlog
                  cpf: 627.820.760-51
                  phone: "+55 41 99868-5562"
                  reg_id: Bx4oyRJ6b3pTC8pn1YFyS
                  credits: 0
                  subscription: free
                  login_id: 8yCapVpTAVxHCuoDjPp7z
                login:
                  login_id: 8yCapVpTAVxHCuoDjPp7z
                  email: dev@pixlog.com.br
                  password: He8ytdfq
                address:
                  level2long: CURITIBA
                  address_id: B5CapVpTAV3HoDSDjPp7z
        '400':
          "$ref": "#/components/responses/400"
        '422':
          "$ref": "#/components/responses/422"
    get:
      summary: Retorna um usuário.
      operationId: getUser
      description: Utilize essa rota para listar as informações de um usuário utilizando
        sua chave de acesso
      tags:
      - 'users: Usuários'
      responses:
        '200':
          description: Consulta realizada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reg_id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  cpf:
                    type: string
                  subscriptions:
                    type: string
                  credits:
                    type: number
                  feedback:
                    type: string
                    format: date-time
                  workspace:
                    type: array
                    items:
                      type: object
                      properties:
                        workspace_id:
                          type: string
                        name:
                          type: string
                  invitations:
                    type: array
                    items:
                      type: object
                      properties:
                        reg_id:
                          type: string
                        name:
                          type: string
              example:
                reg_id: r95CZXQDcz71Xzf5w0OFn
                name: Postman
                email: bruno@pixlog.com.br
                phone: "+10 0 0000-0000"
                cpf: 122.456.789-10
                subscription: free
                credits: 0
                feedback: '2022-07-04T19:01:29.000Z'
                workspace: []
                invitations: []
        '401':
          description: Usuário não autorizado.
          content:
            application/json:
              schema: {}
        '404':
          description: Usuário não encontrado.
          content:
            application/json:
              schema: {}
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
    put:
      summary: Atualiza um usuário através do ID.
      deprecated: false
      operationId: updateUser
      description: Return user information
      tags:
      - 'users: Usuários'
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/updateV1Users"
            example:
              registration_data:
                name: Golxip
                phone: "+55 41 99321-5554"
              address:
                level2long: CURITIBA
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
    delete:
      summary: Exclui um usário específico através do ID.
      deprecated: false
      operationId: deleteUser
      description: Return user information
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      tags:
      - 'users: Usuários'
  "/v1/user/unarchive":
    post:
      summary: "[DESATIVADA] Reverte o arquivamento de um usuário."
      deprecated: true
      operationId: undeleteUser
      description: Utilize esta função para criar novos usuários na plataforma. Usuário
        é uma das entidades básicas do sistema. Ele representa a pessoa física ou
        jurídica que possui uma ou mais assinaturas.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/postV1Users"
      tags:
      - 'users: Usuários'
  "/v1/user/authenticate":
    post:
      summary: Valida um usuário e retorna uma chave de acesso.
      operationId: loginUser
      description: Utilize esta função autorizar os acesso de um usuário a plataforma.
      responses:
        '201':
          description: Sucesso
          headers:
            x-access-token:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/login"
      tags:
      - 'users: Usuários'
    put:
      summary: Extende a chave de acesso de um usuário.
      operationId: refreshUser
      description: Utilize esta função para extender o acesso de um usuário.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      parameters:
      - name: cookie
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
      tags:
      - 'users: Usuários'
    delete:
      summary: Desloga um usuário.
      operationId: signout
      description: Utilize esta função para destruir a sessão de um usuário em um
        ou mais dispositvos
      responses:
        '204':
          '$ref': '#/components/responses/204'
        '422':
          '$ref': '#/components/responses/422'
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
      - name: all
        in: query
        required: false
        description: Destruir todas as sessões ou apenas a atual.
        schema:
          type: boolean
          example: true
      tags:
      - 'users: Usuários'
  "/v1/user/feedback":
    post:
      summary: Cadastra a avaliação de um usuário
      operationId: createFeedback
      description: Utilize esta função para adicionar a avaliação de um usuário no
        sistema.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                rate:
                  type: integer
                  example: 5
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
      tags:
      - 'users: Usuários'
  "/v1/user/validate":
    post:
      summary: Verifica se um email existe no sistema
      operationId: validateUser
      description: Utilize esta função para verificar se um email já existe no sistema.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dev@pixlog.com.br
      tags:
      - 'users: Usuários'
  "/v1/user/password":
    put:
      summary: Requisita uma senha de emergência
      operationId: updatePassword
      description: Utilize esta função para perdir uma senha de acesso ao sistema.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dev@pixlog.com.br
      tags:
      - 'users: Usuários'
  "/v1/user/code":
    post:
      summary: Confirma o email de um usuário.
      operationId: confirmEmail
      description: Utilize essa função para confirmar o email de um usuário.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dev@pixlog.com.br
                verification_code:
                  type: number
                  example: 3210
      tags:
      - 'users: Usuários'
    put:
      summary: Requisita um novo código de confirmação.
      operationId: refreshCode
      description: Utilize esta função para pedir um novo código para confirmar email.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dev@pixlog.com.br
      tags:
      - 'users: Usuários'
  "/v1/report":
    post:
      summary: Cadastra um relatório.
      operationId: createReport
      description: Utilize essa rota para salvar os dados do relatório no banco de
        dados.
      tags:
      - 'reports: Relatórios'
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/postV1Reports"
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
    get:
      summary: Retorna todos relatórios de um usuário.
      operationId: getReport
      description: Utilize essa rota para listar todos os relatórios de um usuário.
      tags:
      - 'reports: Relatórios'
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
      - name: init
        in: query
        required: false
        description: Relatórios apartir da data inicial.
        schema:
          type: string
          example: '2022-01-01'
      - name: end
        in: query
        required: false
        description: Relatórios até a data final.
        schema:
          type: string
          example: '2022-12-01'
      - name: limit
        in: query
        required: false
        description: Limite de relatórios que serão listados.
        schema:
          type: integer
          example: 30
  "/v1/report/:report_id":
    post:
      summary: Envia um relatório para núvem.
      operationId: uploadReport
      description: Utilize essa rota para enviar um pdf do relatório ao cloud.
      tags:
      - 'reports: Relatórios'
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        description: ''
        content:
          arquivo/pdf: {}
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
    get:
      summary: Retorna as informações de um relatório ou o arquivo pdf.
      operationId: getOneReport
      description: Utilize essa função para listar um pdf com informações mais detalhadas,
        caso o usuário queira baixar esse arquivo deverá especificar ao sistema.
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      parameters:
      - name: x-auth-token
        in: header
        required: true
        schema:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBwaXhsb2cuY29tLmJyIiwiaWF0IjoxNjUwOTA0MjAyLCJleHAiOjE2NTA5NDAyMDJ9.oiuVgGaaTIv324-K-X7zk8fzgJyh_Ub_lMURJuT4euo
      - name: download
        in: query
        required: false
        description: Avisa o sistema para baixar o pdf.
        schema:
          type: integer
          example: 1
      tags:
      - 'reports: Relatórios'
  "/v1/debug":
    post:
      summary: Envia um arquivo de depuração para núvem.
      operationId: uploadDebug
      description: Utilize essa rota para enviar um arquivo de depuração para cloud.
      tags:
      - 'debug: Depuração'
      responses:
        '201':
          description: Sucesso
        '400':
          description: Erro
      requestBody:
        description: ''
        content:
          arquivo/txt: {}
  "/v1/static":
    get:
      summary: Retorna informações estáticas.
      operationId: getStatic
      description: 'Utilize essa rota para pegar informações como: telefone de contato,
        email, etc...'
      tags:
      - 'static: Dados Estáticos'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/getStatiV1"
components:
  schemas:
    updateV1Users:
      type: object
      properties:
        registration_data:
          type: object
          properties:
            name:
              type: string
            phone:
              type: string
        address:
          type: object
          "$ref": "#/components/schemas/address"
    postV1Users:
      type: object
      properties:
        registration_data:
          type: object
          "$ref": "#/components/schemas/registration_data"
        login:
          type: object
          "$ref": "#/components/schemas/login"
        address:
          type: object
          "$ref": "#/components/schemas/address"
      required:
      - registration_data
      - login
      - address
    postV1Reports:
      type: object
      properties:
        duration_in_sec:
          type: integer
          example: 392
        latitude:
          type: number
          format: float
          example: -25.438365720891973
        longitude:
          type: number
          format: float
          example: -49.2806723716233
        volume:
          type: number
          format: float
          example: 30.5
        volume_formula:
          type: string
          example: cilíndrica
        specie_found:
          type: string
          example: pinus
        length:
          type: number
          format: float
          example: 3.1
        measure_type:
          type: string
          example: metros
        scanned_at:
          type: string
          format: date-time
        logs:
          type: array
          items:
            type: object
            properties:
              confiability:
                type: integer
                format: float
                example: 0.8903588200176159
              height:
                type: integer
                format: float
                example: 0.28
              width:
                type: integer
                format: float
                example: 0.25
              position_x:
                type: integer
                format: float
                example: 0.12294983577131324
              position_y:
                type: integer
                format: float
                example: 0.1432519030286129
            required:
            - position_y
            - position_x
            - width
            - height
            - confiability
      required:
      - logs
      - scanned_at
      - measure_type
      - length
      - volume_formula
      - volume
      - longitude
      - latitude
      - duration_in_sec
    address:
      type: object
      properties:
        level2long:
          description: Nome completo do estado
          type: string
        level2short:
          description: Nome abreviado do estado
          type: string
        level1long:
          description: Nome completo da cidade
          type: string
        level1short:
          description: Nome abreviado da cidade
          type: string
        neighborhood:
          description: Nome do bairro
          type: string
        country:
          description: Nome do país
          type: string
        countryCode:
          description: Código do país
          type: string
        zipcode:
          description: CEP
          type: string
      required:
      - level2long
    registration_data:
      type: object
      properties:
        name:
          description: Nome do cliente
          type: string
        enterprise_name:
          description: Nome do cliente
          type: string
        cpf:
          description: CPF do cliente
          type: string
        phone:
          description: Número de telefone do cliente
          type: string
      required:
      - name
      - phone
      - cpf
    login:
      type: object
      properties:
        email:
          description: E-mail do cliente
          type: string
        password:
          description: Senha do cliente
          type: string
      required:
      - email
      - password
    getStatiV1:
      type: object
      properties:
        telefone_contato:
          description: Número de telefone de suporte ao cliente.
          type: string
          example: "(41)3095-7300"
        email_de_contato:
          description: E-mail de suporte ao cliente.
          type: string
          example: contato@pixlog.com.br
        link_termo_de_uso:
          description: Link para os termos de uso do aplicativo.
          type: string
          example: https://pixlog.com.br/termos-de-uso.html
        link_politica_de_privacidade:
          description: Link para política de privacidade do aplicativo.
          type: string
          example: https://pixlog.com.br/politica-de-privacidade.html
        link_faq:
          description: Link para dúvidas frequentes.
          type: string
          example: https://pixlog.com.br/sobre/#elementor-tab-title-2261
        link_sobre_nos:
          description: Link para biografia empresarial.
          type: string
          example: https://pixlog.com.br/sobre/#elementor-tab-title-2261
        pagamento_implementado:
          description: Cheque para saber se o pagamento foi implementado no aplicativo.
          type: boolean
          example: false
        modelos_compativeis:
          description: Modelos de celular compatíveis com o aplicativo.
          type: array
          items:
            type: string
          example:
          - iPhone13,3
          - iPhone13,4
          - iPhone14,2
          - iPhone14,3
        data_expiracao_beta:
          description: Data quando a versão beta ira expirar.
          type: string
          example: '2022-12-25'
    BaseError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              details:
                type: string
  responses:
    '204':
      description: Solicitação foi bem-sucedida, mas o cliente não precisa sair da
        página atual
    '400':
      description: Erro de sintaxe JSON no corpo do request.
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/BaseError"
    '401':
      description: Parâmetros únicos conflitam com informações do sistema.
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/BaseError"
    '409':
      description: Parâmetros únicos conflitam com informações do sistema.
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/BaseError"
    '422':
      description: Parâmetros inválidos. Verificar erro na resposta.
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/BaseError"
